// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3XMiNxL/V1S6PNiX4cP27ibh5Q4D652KjSnAuUvZPpc804CyM9KspDEmDv/7lT7m",
	"AxgwbJKtfdg3mJFarVb3r3/dmhcc8DjhDJiSuPWCEyJIDAqE+dfhTBHKQPjhgKiZfhSCDARNFOUMt/AN",
	"o59SQDQEpuiEgkATLpCaAQqyqdjD8EziJALcwvGixqaUPdfKr6mWlGj5HmYk1uPy1w80xB4W8CmlAkLc",
	"UiIFD8tgBjGx+ioFQgv43y2p/d6s/XR/5H7U7l+a3ruTZfb8+F/fYQ+rRaIXkEpQNsXL5TKTtrrhza3m",
	"r5AAyVMRABKQCJB662yKSLFlRJlUhAWAPZwInoBQFIz8QABR8KCo3uX6CmMag1QkTtB8BmzVimhOJLKz",
	"tUEmXMRE4RYOiYKaEaetRMJrFi0yK61t1cM0/KwTLG/nlaOMyfMlsKl2lXdnHo4py/6eeIef1asbSiqd",
	"cpidj35d2tmK+rnWslG5k1fXliCeaGCOkUTR9QS3bl/wdwImuIX/0SiiquHcqzGyE3w24Xh5v76ClphA",
	"oMXtEpJ74UgP1pMUUancX4tCgJ1YqUmahH/CTSMiFbIiPtdXl+WYv7WWuc9H8cffIFDYw881Akkti8cS",
	"Hkg9q3TEL2VAWWpRSZQKEq04AvawpGyaRkSUnxeg8fFHWfhIzTlALRH8iYYg6mEQ1ylvFBP1NnJ7d5LU",
	"nFIYUm1IEg1KyGCNsAY4g5sCagLOpBKEapheB5WYPG+e0hV5pnEaIxJFfA4h0tICLkBPjynT70xQuq1R",
	"pmCqVTZvK8TZKWiaEkGYggMkrp2lFm+AYvNAy+bqsadfiDjMYj32RAVnMTCFnoig5DECFMKEMiNgw3A2",
	"2bzsI8UMrUCBJxKl+8qwY1/zdbeSHbzTRH5MpnCgTxWYricjHVh0QgNSaR8BExDAAqjKhhpHFaDrju9k",
	"5aPrd+y9ifkWuh32LvzRePhr437YG1yP/PH18Nfb1rh98ce/u/5FbzS+v2MruPwpJQsdRfGCJEnr6aR+",
	"+qrFCjV3muuSSrW5kQGZUqaRCkVUKsQnFXlPoqN2b1A7OTtFWoiOyoQzCcebHgXP6iEhU3hQ/CNUxNFY",
	"PzYpVoASFJ40ddAQqmciPVOrIECmkYn0DYfLXrVeMFUQy70Thp7spBEhyKLCjFbyTiNeQczF4jCns3P+",
	"QiyLrcA5VTOUMqrQEdSndQ/d4dOL8zusf7zRP8z5lEiHZhbfH12d/3Fx/sf4/Pi7Kvvui37bdTjJdDj9",
	"PB0+Dy+vQJGQKLKDDsVuiHG/jBZtCf2IPEIkt5/zy6bl1gAilYrH6CMsagbKUEKokJZckunUMGYWogmN",
	"FBgJFZurxud8P/r1Kr07nH7W3K9/7qwSrCoyIVVQ+HP6CIKBAonyUZoaCchdXqK5/lvw98Poj7HDztPv",
	"g5pz8fGwuHSTdDxO6DQV1Z5AkwrQ5CHyB4iEoQAp92LqXFjQ2paPzACkOILnhEudAQ+DtwEXqhLithvN",
	"TPnM9KnV3UUtCr6ZuFXWLSgUYmn8aNMMDVcr5tgiHm69e/v27O1rjO2JSvpII6oWmwt94HOkZlRajal0",
	"9g21qTUQpzEIWb9jNcQ4gxYauGGMq3woT5XRcJXqJ4IHIKWeqnURjEQt1Cuk69EzrnOqQEGUSgUCMety",
	"dwxleNnlwUcQqJZ4qBRIHTveHyBXNR3rZeA5W2YIJJgZUjURPF5RUC/ZcOuV1rlOgI1mdKLQkKcKVlbz",
	"2VT7ceOSk/CcRDrli2PLS5g2+i3WtjGdCquAYSzu532ZvZQG7A7pNf9YOcOdkT6wVv9sv7XTX4l5IqYV",
	"wdoW01QzWpmdLjAlFgmnTJXDdSP2V0PSwwGPY8LCKtacyUP8CYSgIRwkGNjTflRcHgwvrhw5DGCyTCUP",
	"L/x0bowP4E2BrS732ouuRDXTyancXrMc89tw5CTFuaydnjty7Y1trrlSi1hiRVmSKjShEIWWOpgMutZt",
	"28xYWV20175sFWXsUTCoPS3iJmh+UCTgveZmCXtplM8ier9M58bbqab18DCjrn+7v5ddJ3YcyoTUsgNA",
	"RppFVgP5RJGIT9ERCQJIFISeyQ4k0FVTmnB2XEXeRNn599pYES5Fe+3Byl33GpcVkH5b7l0exalU6BHQ",
	"XYGwloNnSF64zf2rXaeyCiX/8JyHlfe42/PzHt06RxZCw5Lt4enCb3vf1ak/6PW7fv8Ce3h40+/bX+/b",
	"/mWviz180/+5f/2fPvZwt3fZG/e6FXv0cE8IXtHfHr7voB9+bP6A9BFFlDCFQI/Mq92NOAtBERpVUI40",
	"JqymKaHJ0PCcRITZqM5dzGQQKhEPAmOEoLK7khtg77a1JjhG6xXBeQsyFbRWtAuqurpbjurDeDzIzing",
	"4YpQytRZqUtRImaKqqjKe2eaZM1WzSTTOCZiUaVUdQyYc7QR4DTKnMTv/9K+9LsP7eHFzVWvP8Ye7l+P",
	"H95f3/S1m7Qvh71299eH3n/90XiEPTzoDa/80ci/7j90e33f+VL7Zvyh1x/7nfbYPPH7496w3760L39p",
	"+5ft88uedrF9zbsWXy6urJGqAugDkKiqwW+fZ8chKZtGoDjLM+WGp1bfE3QI44wGGgKJmmXhVxJS8LqZ",
	"1WSfa4FtDlTWuUL2AQefF8Br6Lcidb9edb6vrUf46obTpPqaYAQBZ6E5nsAyc6dEnnC0MYSth3O9z941",
	"m1sXLZc8IKRZZ1tmyBd5TGkUomx82UQn9Wa9eXAx7rw2P0h3cVks4Axy8HWFO4vy3YR9lF1MGCfPr0CL",
	"m4r8EA+6pnCz9PbKN1O72huZbS3wV5BQW3U9VLUMXEVXyyqk1f7Bhldl5VWlrN7zhgx0pPG/XMCZ6Dje",
	"1svZFNonMWQYsLnnP9HjyD3SvN6z8HCTqrsa24ChzIpK6SAvpnUe4KEV6uGysarJ0AYgl7Xauc+tLpK8",
	"PtV2RSrzaSK44gF3nGNC0khD1rijd7bWX3Ej0dG4M/DQTXdQ6QqKiCmoLT2asXlZ7nhYw71ywZWNKone",
	"TG5Lw25svJkFAlXcSOFu5woNBHewkQqDBUolstVoTKmapY/1gMeNMIh1WOthjd1Bv9mf1UtsALKOoZgw",
	"YtqzxcUooqwcEi7MZf2OjTXhag98NOFRxOcStXuGJrGQiKxk40xSqYAFC0QCwaVEpbW1EOzhiAagKWZh",
	"gnZCghmgU4PQqxaYz+d1Yl7XuZg23FzZuPQ7vf6oVzutN+szFUclBlZGsaLizNxukO2/PfBLUJ5liKWH",
	"eQKMJBS38Fm9WX/jYN94dIMktPF0QqJkRk4apdvk1guegqpK3+biBxDZvHKStu5N7KWUYcxp4hxKh5F5",
	"5oe4hS+pVJ3y1XX5y53bbTcoruNor5hca1pxJEClguljJo5Omauo7NucTykYYuqOJibP9o5L0t9NKsy/",
	"xslj8m2zgh/nTc2Tpk7yu++Mqy/OKAtNg8BdmhkCof/YplH25coO3Ut3c2XF17HPfBRhyx5zkKfNZhap",
	"wGzTOEki16to/CYtEynk7VXvmgtJgwRraJgGusCfpFG0yK4JISw5ifbINzs1SgR/jCD+/jDNbGVYodE5",
	"CZGGOJDKrn3y5dZup2qmGa7rC+VIa/Q4+3J6DEDEVGpgQCEwajV4+yVPwc+ok8ZOELbQNeknqx0tLKAV",
	"XFBkauhl6eG9IStVt+Edc0OFCGIwr25ErKKQHd8pt+J2wVDecwoiCkxlHScIkd/d/O6sjvyJ6TS5/BR6",
	"dyyrI0CgOY0iNAWm9QFEGPK79Tt2x4bWQ2yn+ijRsN4b1E5OT49bd6yGTmrvzlAwI4IEWksUcTbVz0ca",
	"Syz8EhTxOYiASEARaIaOuEAhnVKlR7rtIs6ixcZI6TmQlZ5p4s4WyQyYuSXpsdDKL2TaoWufQGz/SHIN",
	"zMy3kYVT/bUf31VCooGAcx4u/no0tB6/+qXncgOGT/6uhbd1pd2dLZIlUP6Gv18L/r5p/vTlNOhwNolo",
	"oFANdSGJ+MLcKZmIlrp4NN8jkEjXiQsEz1Qq+VXmCAfyZdSuTBJLbyu5zboHOzhuKpi0F7Ir3TpXYcu8",
	"rF5NKBegPhS9tr+JgX3IWh+b1MtVBFSirC23ajvXxuvMIPhYspuTuNtmax+hGqNFoCoK+a55rsl41i/f",
	"IxfbSTtycZVJiiGN9Y/9K0jwm133d3YzVUj5Da0yDd58UbRyB6Mp1ISn7OtkrM7XX0Uj79VqekewoMcF",
	"8rtVaPO3xkvzS7OVolr8FoXfovCAKLwAtQchcPfy1cXdzz/u6q3lXbyGCRQnf8stWaDTK8pjVRYlT5a6",
	"ve15KKITCBZBBLaVaQrBSlmlvS3vl/8PAAD///K743kKNwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
