// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW3PjtpL+KyhsHjwb6mLPJYledmVZ42HFllW2nN3U2McFky0JMQlwANC2MtF/P4UL",
	"LxIhWZqTmcrDvMkg0Ox7f92gP+OIpxlnwJTEvc84I4KkoECYvwacKUIZiDAeEzXXSzHISNBMUc5wD18z",
	"+ikHRGNgik4pCDTlAqk5oKg4igMMzyTNEsA9nC5abEbZc6v+mGpKmaYfYEZSvS+qXowDLOBTTgXEuKdE",
	"DgGW0RxSYtlVCoQ+/6+PpPVnt/XL7YH70br93A3eHS6L9Vf/8wMOsFpkmr5UgrIZXi6XBbVVeZuSlo+Q",
	"AMlzEQESkAmQWnI2Q6SSGFEmFWER4ABngmcgFAVDPxJAFNwpqoVcf8OEpiAVSTP0NAe2qkT0RCSyp7VC",
	"plykROEejomCliGntUTiC5YsCi2tiRpgGn+RAevivGDJlDyfAZtpT3n3OsApZcWfh8H+tnpZoJTMjCJ/",
	"EDDFPfxfncqZO86sncqHze5lgFNQJCaK7HzyvDiwDDAD9cTFw85nR27/MrAu3rDAZeFO+nHNECvaLpUs",
	"O17Fv6iqTPAIpNyZ7bHbb48+0hjEB+pyxDYC45XNS82ZFW/3V1+WJ3RwgnikkTEySZKLKe593E7myh4I",
	"2ZTj5e26ZiqKE6OhdWO400jrrx4UB2kuFboHdFOZ4ga/0jZieYp7H6tlfOtRv1RE5XJ3KUplXNmDXkny",
	"LP4PsklCpEKWxJemlGU9NX9c0Wwtyoo4rftCpSN+/wdECgf4uUUgaxVbasldrqhXdj6Xv+9ovNSksiQX",
	"JFkJExxgSdksT4ior1cV4OFnWUVQy7HeKny9HUdpm/JOdVALW1plkOWeCjG+rmpDxJlUgpgoWK8CKXlu",
	"nj4nzzTNU0SShD9BjDS1iAvQx1PK9DOTRR37lCmYabbMUw85ewTNciIIU7AHxTWravImszeNVlfJkD3+",
	"Rjx1c8geqeAsBabQIxGU3CeAYphSRs2OdeVYALATFbPVE2yPJMl3pWH3vuTZ7k1281Y1hEVJ2oQeTCwg",
	"mUFEpzQiXh0ImIIAFnkJ6YqgAF0MQker3N2+Ye9NFPfQx8vhaXg1ufy9c3s5HF9chZOLy98/9ib907/+",
	"9yQ8HV5Nbm/YSoX5lJOF9vh0QbKs93jYPnpRKxWbW1VyRqVqCjImM8p07kEJlQrxqQdwNEOnFuC9z5gq",
	"SHevK5opxyURgixsNX9WdxmZwZ3iD+CJo4leNphIgBIUHjXW08lUn0T6pGZdgMwTE+lNjW1WzDmkXCw8",
	"sWvW/8ZcklqCT1TNUc6oQgfQnrUDdIOPTo9vsP7xRv/Q9ayO0jQU+/Hg/Piv0+O/JsevfvAF267ZZzMP",
	"hwUPR1/Gw5flq/MaCNwAyIoKZsxfgIENIZuQe0hsgY9jk9lIMl7Z0dDcWmDnUvEUPcCiZdIMyggV0qJx",
	"MpuZFoPFaEoTBYaCRzh/7izl0Y9XAaYXkrfcr//e2jnZt8mM+LLUr/k9CAYKJCp3aRwioPRqiZ70n1VP",
	"sx/WMKJuNfCoAuqrzLkHOqymdJYLv0Fp5slZPEbhGJE4Fhob7wK7ubCYeVM5MBuQ4gieMy51kdkvqY25",
	"UM3EtqYsy8VWbRk6L/C5rWxH2wnpVcTy9N5mdxqvDghSm7Bw793bt6/f7gVPVl+8XcaqB9oopt3ygm8Q",
	"MfNQ6YtZrsGFMacuEcCUWGScMlU3a8NH1mtSxNOUsNgHYAp6iD+CEDSGvQgDe9wNFcm93dChP58jbrbH",
	"Zb01bGJpne7SPUphZEH5TvxqAG8mAUUF3nEOYLY3XDDLcUlrqwdelW3gevIXQhvAtokaUWyewLh+czwc",
	"nYSjUxzgy+vRyP563w/Phic4wNejX0cX/zfCAT4Zng0nwxNvUzoUgnsQ++X7Afrp5+5PSKsioYQpBHqn",
	"tkLGmWyOtWJQhCZNSh/ylLCWTpIGa8NzlhBmQqoEwDZWqEQ8iowSIi+kLxWw8wCLSsf1CuGyy80FbVX4",
	"dWvHvibTZDIu7BTxeIUoZep1DTbXejRFVeIbN8x1XpyvqknmaUrEwseU8g4tjB3tyMJxVDhJOPqtfxae",
	"3PUvT6/Ph6MJDvDoYnL3/uJ6pN2kf3Y57J/8fjf8//BqcoUDPB5enodXV+HF6O5kOAqdL/WvJx+Go0k4",
	"6E/MSjiaDC9H/TP78Ld+eNY/PhtqF9tVvWsBpOzEwCrJF0AfgCS+2ZldL8yhG/4EFGdlvmh4qn8ENyCM",
	"MxqRxM7gXPjViFRt0txyskPp10zBVpZ9lPcwe4nr1oZVK1R3G3OUUm004H7ozBm0ENJofe+Rj2OqPt+x",
	"S8Vwx9i6vBOopj2lNHuNetwpLUoFX8frs89NOLdVJrSCLpp7q1RtoLmt5lSU3UjSDVR9BXXD3m2ovJhz",
	"ruCcDRwD02nJg0cuHAhBV2MNDUmeKHSgraGTugX2AZqSRJoF+UCzV5VR7jlPgLDN7r0yij0YJLlUIMJx",
	"gEY8Bg32AnTGSXxMEl0YRH0WW27W+c7txgGub/cURJ9qG/Z/oburTq6pKrOHSu+o/GXFBO0bVrxSolyC",
	"NYlORxoERXzG6J9gkBGdMS4A5eyB8SdnuvZNE6s+lEbf3eXWhvg+xdTH7Ls4moUIHtBWmqqZle2jli6j",
	"QutupfVqJEl4ttt8pIbPDRLoQOOEuksYT3uFd+/iCtns4x0hszvk79t2iYWv4ud1rrbKudGQ2ctHbf/n",
	"xUeZ4IpH3GFIk0pwD08GWrK1TtLtRAeTwThA1ydjr8kUETNQfnkm5lkNXmdWb55Oc01RSwNFrcub45Gq",
	"Ztb4ZHCOxoK74pYLU7GUymSv05lRNc/v2xFPO3GU6uKjt3W2l6ZmHtGvkIVOi0KjHTkljJghUTUhRZSh",
	"WiS6SNNJYqLRcX8coilPEv4kUX9oMC2LiYjtzEk3WlQqYNECkUhwKVHt3S7TJDQC3Q9UKuhnJJoDOmp3",
	"Gxp4enpqE/O4zcWs487Kzlk4GI6uhq2jdrc9V2lSg8v1RFL16IVPFVlKS4ID/AhCWiUdtrvtribDM2Ak",
	"o7iHX7e77TcOiRh37axOkmegfADLTHwBkeaMWtpJZman2KajyTPnRzoszFoY4x4+o1IN6vdS9U8sPq6/",
	"872Z7+lWSScpTddZozpvPpf4lINpEZze7VgQ1z+NaET9pimxG8vYMbabzSmOBKhcMO1ExCFrM+7ewEBK",
	"nu0cXdI/YYWPMpzfdj2tUjn5Oex2uy8NfvzDecpiM5V1g3mpiDB/2ElJ8TnDFt5r8/9tCjRXsLYDNj5z",
	"1O0WeQCYcR+SZYkbEHf+kNwMxit6O40YzGWJyTNriTSPIpBymifJoriKgLjuGMsAv9nKUSb4fQLpj/tx",
	"ZocEHo6OSYw05gep7LsPv927+7ma63bHUkdl62H4eP3t+BiDSKkN0xgYtRy8/ZZWCAtwpDOzThxuY4CL",
	"MYLNQGglBSkyMy1WbfHW4BzfTd3AIHlEEIMn/0xqNeHZ/YPaeHdrxiuhcZRQYKoAxhCj8KT5MVIbhVPE",
	"uCqqXxzcMBP1VvwnmiRoBkzzo3EyCk/aN+yGXVoPsePZg0wXjeG4dXh09Kp3w1rosPXuNYrmRJBIc4kS",
	"zmZ6/UrnEpvpE/4EIiISUAK6R9WPnYyIs2TR2CADl1llYAD7fJHNgUl9bshiR9TsRFy4rWt3spu/llvL",
	"YDReyVz7fIa15/dyt7bRB6mOebz4+/Of9fHVD/6WjcR7+LVevOlewF1TIVlLw98z7j8l477p/vLtOBhw",
	"Nk1opFALnUCW8IW5OjHhLEnqbllJIoDECwTPVNrv4P5xVcGl9Xqe9paFZVAHy7Wvr8J4aYtFAr5B54lZ",
	"1+CxNul4qXbYQ1tqh08d1ZbO+gfLHtD2Ztv9nxXGF+ffY63g4M03jTVnGF3ypzxn/0yE5Xz9xVgKXmw0",
	"twQLul+g8KQRMqegvmq8dL91ra26m+9R+D0K94jCU1C7lbN5eZ24KRxzwczUHc1XbhjdzWBxh+MJxQ/V",
	"/eBXiqIPxT1Vc0bgBmNUouIycVVB7u5xMIfooaYfR/HW/jeM0a+vUeuPQ/R4SJJsTg7L6V6HZLRTrur0",
	"4ahuuPeM9LtRqTZZ9TCFXMHm6pzQKUSLKAE77jTtnJdWzeLL2+W/AwAA//8K6/vv5DQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
