// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb2XPjNpP/V1DYPHg21GHPkUQvu7Kk8ahiyypbzm5q7M8Fky0JMQlwANC2MtH//hUO",
	"HhKha77MVB7mTSYbjUafv27Qn3HIk5QzYErizmecEkESUCDMXz3OFKEMxDAaEzXXjyKQoaCpopzhDr5h",
	"9FMGiEbAFJ1SEGjKBVJzQGG+FAcYXkiSxoA7OFk02Iyyl0b1NdWcUs0/wIwkmq54fU8jHGABnzIqIMId",
	"JTIIsAznkBArr1IgNIN/fSSNP9uNX+6O3I/G3ed28O54mT9/9T8/4ACrRao3kEpQNsPL5TLntnrg+lGL",
	"V0iA5JkIAQlIBUh9dDZDpDwyokwqwkLAAU4FT0EoCoZ/KIAouFdUn3J9hwlNQCqSpOh5DmxVi+iZSGRX",
	"a4VMuUiIwh0cEQUNw05riUSXLF7kWlo7aoBp9EUWrB5nhykT8nIObKZd5d3rACeU5X8eB4fbaveBEjIz",
	"ivxBwBR38H+1Sm9uObO2Sic21MsAJ6BIRBTZe+VFvmAZYAbqmYvHvdeOHP0ysD5es8BV7k76dcUQK9ou",
	"lCxbXsXvVFUqeAhS7i322NHbpU80AnE/py5LbOMwdtQfDPFSi2bPt//eV8UKHZ0gnmhorEzi+HKKOx+3",
	"s7m2C4ZsyvHybl01Jcd7q6N1c7jlSL+thsVRkkmFHgDdlsa4xa+0lViW4M7H8jG+8xhAKqIyuf8xCm1c",
	"24Xeo2Rp9B/kk5hIhSyLL00qy2py/riq2kqg5aFa9YZSSfzhDwgVDvBLg0DayEkq+V2u6Fe2PlcLxFKz",
	"SuNMkHglUnCAJWWzLCai+rwsAo8/yzKIGk72Ru7uzShMmpS3yoX6tIVZemnmKRLjm7I8hJxJJYiJg/VC",
	"kJCX+uoL8kKTLEEkjvkzREhzC7kAvTyhTL8zidSJT5mCmRbLvPWws0vQLCOCMAUHcFwzq2ZvknvdaFWV",
	"DNjTb8RTOgfsiQrOEmAKPRFByUMMKIIpZdRQrCvHgoC9uBhST7Q9kTjbl4el3eXabidLvFUNw7wqbQIQ",
	"JhaQTCGkUxoSrw4ETEEAC72MdFFQgC57Q8eroG7esvcmjDvo49XgbHg9ufq9dXc1GF9eDyeXV79/7Ey6",
	"Z3/9b394Nrie3N2ylSLzKSML7fHJgqRp5+m4ebJTK6WYW1VyTqWqH2RMZpTp5INiKhXiUw/mqIdOJcA7",
	"nzFVkOxfWbRQTkoiBFnYgv6i7lMyg3vFH8ETRxP92MAiAUpQeNJwT2dTvRLplVp0ATKLTaTXNbZZMReQ",
	"cLHwxK55/jfmksQyfKZqjjJGFTqC5qwZoFt8cnZ6i/WPN/qHLmhVoKbR2I9HF6d/nZ3+NTl99YMv2PbN",
	"PptlOM5lOPkyGb4sX11UcOAGTJZXMGP+HA1sCNmYPEBsK3wUmcxG4vEKRU1za4GdScUT9AiLhkkzKCVU",
	"SAvIyWxmugwWoSmNFRgOnsP5c2dxHv16FWOuQXYvSG+4X/+9tZeym8uU+JLWr9kDCAYKJCqoNC4RUDi5",
	"RM/6z7LLOQx7mJNvtfeohO6rwrkXOsqmdJYJv31p6klhPELDMSJRJDRa3geIc2FB9KbqYAiQ4gheUi51",
	"zTksx425UPU8t6YsK8VWbRk+O+TcVsVLiJZ6OWn+iGXJg832NFodGiQ2geHOu7dvX789CK6s7bz9lGVf",
	"tPGglmSHdxAx83Dpilmm0YYxqK4ZwJRYpJwyVTVszUvWi1TIk4SwyIdocn6IP4EQNIKDGAN72g8myYMd",
	"0cFBnytutsdVtVusg2ud/5IDamNoUfpe8mpEb6YDeUneczZgyGs+mGa44LXVA6+LxnC9GgihDWAbRw0x",
	"Nk9lXAc6Hoz6w9EZDvDVzWhkf73vDs8HfRzgm9Gvo8v/G+EA9wfng8mg721TB0JwD4S/et9DP/3c/glp",
	"VcSUMIVAU2orpJzJ+qgrAkVoXOf0IUsIa+g0acA3vKQxYSakCkRsY4VKxMPQKCH0YvxCAXsPtah0Uq8w",
	"LvreTNBGCWi39vBrZ5pMxrmdQh6tMKVMva7g6ErTpqiKfQOIuU6M81U1ySxJiFj4hPKPMYwd7RDDSZQ7",
	"yXD0W/d82L/vXp3dXAxGExzg0eXk/v3lzUi7Sff8atDt/34/+P/h9eQaB3g8uLoYXl8PL0f3/cFo6Hyp",
	"ezP5MBhNhr3uxDwZjiaDq1H33L78rTs8756eD7SL7avetQByIwSrJF8AfQAS++Zp9nluDknZLAbFWZEv",
	"ap7qH8v1COOMhiS2czkXfhUmZd80t5LsUfw3OlBVZg/vAwxfQL21AdYK1/0mH8W5Nppw54Gz1D+buoaQ",
	"s8iYR4s6B+SEQLkQWhnC4sBC7tfv2u2Nm1Yi6wmENPtsGu4VmzxkNI5QTl9V0XGz3WwfDEKd1xaGdNca",
	"5QZOIQcPv5wtqpMu+ygfcxknLy5IyrlXYcSDhl5ulT5eidxXR7tbIH6jyOSFoufe8lwZ7m4rtiVnZ0A3",
	"XPYhiQ202xqS3CtWAN4GiYHpfOwBYpcOfaHrsUbFJIsVOtLW0NXM9jQBmpJYmgfykaavSqM8cB4DYZuj",
	"emUqfdSLM6lADMcBGvEINJIO0Dkn0SmJdUUU1bF0QawTvaPGAa6Se5CAT7U1++/oc8uVa6pK7aLCO0p/",
	"WTFB85blW0qUSbAm0dlCo7+Qzxj9EwwkpDPGBaCMPTL+7EzXvK2D9MfC6Pu73NqFhk8x1SuHfRzNYiMP",
	"WrWmuvd1ms6MDZ3mhFbeSttZS7zwYsm8vAYvNR7oSEOkqlMYX3uF929hi+RqXu/ZLbhF/qZ1n2j4Kp5e",
	"lWrrOTeaMt291Pa+XmiYCq54yB18NskEd/Ckp0+21kU7SnQ06Y0DdNMfe02miJiB2tCJT8zLSmuRWsXt",
	"aLNzqgrrOk5bGqBu48JsEKpyxI/7vQs0FtxVwEyYsqZUKjut1oyqefbQDHnSisJEVyhN1tpev+rJRm9R",
	"wxba1xPCiJmplQNlRBmqhKsLR51JJrp36I6HaMrjmD9L1B0YxM8iIiI7otNtKJUKWLhAJBRcSlTZ26Wj",
	"mIagu6VSBd2UhHNAJwZsrGrg+fm5SczrJhezllsrW+fD3mB0PWicNNvNuUriSjNRzTblBCN3uzyV6ZNU",
	"UEkOdpYB5ikwklLcwa+b7eYbh2CMR7dISltPxyRO5+S4tTqFn4HyIVEzLQdE6vN9aafAqb0BMM1fljqH",
	"0mFkng0j3MHnVKpe9U6v+onKx01jbzdXsnN5N11UHAlQmWDazMR1BmZ+n3+E8ikD02M50yTkxV4MSPqn",
	"QXXFZydFTL5te1q9YnR13NZ4dfvkyn/bQFlkxszupsFgYf2HnfTkn2hskb1yoVEVfD33mUtl28EbQ560",
	"23mkAjM2JWkau4l36w9pQXXJb68Ribn9MZlgLRtmYQhSTrM4XuR3KxBVnER75JutEqWCP8SQ/HiYZHbI",
	"4ZHolERIpziQyu59/O327mZqrps1yx0VmdbI8frbyTEGkVCpEwOKgFErwdtvaYVhDnF07gRhZzam/ORj",
	"EJsW0EpeUGRmOqXKwzsDVnxXjz0DyBFBDJ79M7XVLGTpe5X59NY0VCDcMKbAVI5vIULDfv0DqyYaThHj",
	"Kq9PUXDL8pYYBHqmcYxmwLQ8Gu6iYb95y27ZlfUQO14+SnVaH4wbxycnrzq3rIGOG+9eo3BOBAm1lCjm",
	"bKafX+tcYtNvzJ9BhEQCikG3mvq1OyPiLF7UCGTgMqsMDO6eL9I5MKnXDVjkmBpKxIUjXbtk3vwJ4FoG",
	"M1/+lZ50yKdlB34DeGdxDUh1yqPF35//rI+vfsS4rCXe46+18aZ7DXfRhmQlDX/PuP+UjPum/cu3k6DH",
	"2TSmoUIN1Ic05gtz9WPCWZLEXRuTWACJFgheqLSf9v3jqoJL69U87S0Ly2AjnF3/tsyUjhiUpw3tm+ca",
	"SlbGF7sqiV20pZL4lFOStNa/yfZAuDfbbjPtYXxR/z3ycgnefNPIc4bRAGDKM/bPxFvO13dGVrCzF9wS",
	"LOhhgYb9Wsicgfqq8dL+1pW37HW+R+H3KDwgCs9A7Vfc5sXl6KZwzAQzo3Q0X7kvdfec+cWMJxQ/lLed",
	"XymKPuSXT/WJgRtkUYnyi9FVBbmL1N4cwseKfhzHO/v/Pka/vrbt15+3Tc2K+VzLJBHHe8NVbqglQIXy",
	"ZNnX5KcLNtfomE4hXIQx2CGlafG8vCp2X94t/x0AAP//yzQ3As01AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
