// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ContainerServiceType.
const (
	ContainerServiceTypeContainer ContainerServiceType = "container"
)

// Defines values for ContainerStatus.
const (
	DELETED ContainerStatus = "DELETED"
	FAILED  ContainerStatus = "FAILED"
	PENDING ContainerStatus = "PENDING"
	RUNNING ContainerStatus = "RUNNING"
	UNKNOWN ContainerStatus = "UNKNOWN"
)

// Defines values for ErrorType.
const (
	ALREADYEXISTS    ErrorType = "ALREADY_EXISTS"
	INTERNAL         ErrorType = "INTERNAL"
	INVALIDARGUMENT  ErrorType = "INVALID_ARGUMENT"
	NOTFOUND         ErrorType = "NOT_FOUND"
	PERMISSIONDENIED ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED  ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE      ErrorType = "UNAVAILABLE"
)

// Defines values for KubernetesServiceHintsType.
const (
	KubernetesServiceHintsTypeClusterIP    KubernetesServiceHintsType = "ClusterIP"
	KubernetesServiceHintsTypeLoadBalancer KubernetesServiceHintsType = "LoadBalancer"
	KubernetesServiceHintsTypeNodePort     KubernetesServiceHintsType = "NodePort"
)

// Defines values for ServiceInfoType.
const (
	ServiceInfoTypeClusterIP    ServiceInfoType = "ClusterIP"
	ServiceInfoTypeLoadBalancer ServiceInfoType = "LoadBalancer"
	ServiceInfoTypeNodePort     ServiceInfoType = "NodePort"
)

// Container Container resource representing a container instance
type Container struct {
	// CreateTime Timestamp when the container was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the container instance
	Id *string `json:"id,omitempty"`

	// Image Container image specification
	Image ContainerImage `json:"image"`

	// Metadata Resource metadata for identification
	Metadata ContainerMetadata `json:"metadata"`

	// Network Network configuration
	Network *ContainerNetwork `json:"network,omitempty"`

	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// Process Container process configuration
	Process *ContainerProcess `json:"process,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	// Providers use hints they recognize and ignore unknown hints.
	ProviderHints *ProviderHints `json:"providerHints,omitempty"`

	// Resources CPU and memory resource constraints
	Resources ContainerResources `json:"resources"`
	Service   *ServiceInfo       `json:"service,omitempty"`

	// ServiceType Service type identifier (must be "container")
	ServiceType ContainerServiceType `json:"serviceType"`
	Status      *ContainerStatus     `json:"status,omitempty"`

	// UpdateTime Timestamp when the container was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// ContainerServiceType Service type identifier (must be "container")
type ContainerServiceType string

// ContainerCpu CPU resource constraints
type ContainerCpu struct {
	// Max Maximum allowed CPU cores
	Max int `json:"max"`

	// Min Minimum guaranteed CPU cores
	Min int `json:"min"`
}

// ContainerEnvVar Environment variable definition
type ContainerEnvVar struct {
	// Name Environment variable name
	Name string `json:"name"`

	// Value Environment variable value
	Value string `json:"value"`
}

// ContainerImage Container image specification
type ContainerImage struct {
	// Reference Complete OCI image reference.
	// Format: [REGISTRY/]REPOSITORY[:TAG|@DIGEST]
	Reference string `json:"reference"`
}

// ContainerList Paginated list of container instances
type ContainerList struct {
	Containers *[]Container `json:"containers,omitempty"`

	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ContainerMemory Memory resource constraints
type ContainerMemory struct {
	// Max Maximum allowed memory with unit (e.g., "2GB", "4GB")
	Max string `json:"max"`

	// Min Minimum guaranteed memory with unit (e.g., "1GB", "2GB")
	Min string `json:"min"`
}

// ContainerMetadata Resource metadata for identification
type ContainerMetadata struct {
	// Labels Custom key-value pairs for tagging and filtering
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Resource name identifier
	Name string `json:"name"`

	// Namespace Kubernetes namespace where resources were created
	Namespace *string `json:"namespace,omitempty"`
}

// ContainerNetwork Network configuration
type ContainerNetwork struct {
	// Ip Pod IP address
	Ip *string `json:"ip,omitempty"`

	// Ports Container ports to expose
	Ports []ContainerPort `json:"ports"`
}

// ContainerPort Container port definition
type ContainerPort struct {
	// ContainerPort Port number inside container
	ContainerPort int `json:"containerPort"`
}

// ContainerProcess Container process configuration
type ContainerProcess struct {
	// Args Arguments to the entrypoint
	Args *[]string `json:"args,omitempty"`

	// Command Entrypoint override
	Command *[]string `json:"command,omitempty"`

	// Env Environment variables
	Env *[]ContainerEnvVar `json:"env,omitempty"`
}

// ContainerResources CPU and memory resource constraints
type ContainerResources struct {
	// Cpu CPU resource constraints
	Cpu ContainerCpu `json:"cpu"`

	// Memory Memory resource constraints
	Memory ContainerMemory `json:"memory"`
}

// ContainerStatus Current status of the container instance
type ContainerStatus string

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type Error type code
	Type ErrorType `json:"type"`
}

// ErrorType Error type code
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status string `json:"status"`

	// Type Resource type identifier
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since the service provider started
	Uptime *int `json:"uptime,omitempty"`

	// Version Service provider build version
	Version *string `json:"version,omitempty"`
}

// KubernetesProviderHints Kubernetes-specific provider hints
type KubernetesProviderHints struct {
	// Service Kubernetes Service configuration hints
	Service *KubernetesServiceHints `json:"service,omitempty"`
}

// KubernetesServiceHints Kubernetes Service configuration hints
type KubernetesServiceHints struct {
	// Enabled Override SP default (true to create, false to skip)
	Enabled *bool `json:"enabled,omitempty"`

	// Type Service type (ClusterIP, NodePort, LoadBalancer)
	Type *KubernetesServiceHintsType `json:"type,omitempty"`
}

// KubernetesServiceHintsType Service type (ClusterIP, NodePort, LoadBalancer)
type KubernetesServiceHintsType string

// ProviderHints Optional provider-specific configuration.
// Providers use hints they recognize and ignore unknown hints.
type ProviderHints struct {
	// Kubernetes Kubernetes-specific provider hints
	Kubernetes           *KubernetesProviderHints          `json:"kubernetes,omitempty"`
	AdditionalProperties map[string]map[string]interface{} `json:"-"`
}

// ServiceInfo Kubernetes Service details
type ServiceInfo struct {
	// ClusterIP Cluster-internal IP address
	ClusterIP *string `json:"clusterIP,omitempty"`

	// ExternalIP External IP address (for LoadBalancer type)
	ExternalIP *string `json:"externalIP,omitempty"`

	// Ports Service ports
	Ports *[]ServicePort `json:"ports,omitempty"`

	// Type Service type
	Type *ServiceInfoType `json:"type,omitempty"`
}

// ServiceInfoType Service type
type ServiceInfoType string

// ServicePort Service port details
type ServicePort struct {
	// Port Service port number
	Port int `json:"port"`

	// Protocol Protocol (TCP, UDP)
	Protocol *string `json:"protocol,omitempty"`

	// TargetPort Target container port
	TargetPort int `json:"targetPort"`
}

// ContainerIdPath defines model for ContainerIdPath.
type ContainerIdPath = string

// ListContainersParams defines parameters for ListContainers.
type ListContainersParams struct {
	// MaxPageSize Maximum number of resources to return in a single page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token indicating the starting point for the page
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateContainerParams defines parameters for CreateContainer.
type CreateContainerParams struct {
	// Id Optional client-specified ID for the container. If not provided,
	// the server will generate an ID.
	//
	// Requirements (per AEP-122):
	// - 1-63 characters long
	// - Start with lowercase letter
	// - Contain only lowercase letters, numbers, and hyphens
	// - End with letter or number
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateContainerJSONRequestBody defines body for CreateContainer for application/json ContentType.
type CreateContainerJSONRequestBody = Container

// Getter for additional properties for ProviderHints. Returns the specified
// element and whether it was found
func (a ProviderHints) Get(fieldName string) (value map[string]interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProviderHints
func (a *ProviderHints) Set(fieldName string, value map[string]interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProviderHints to handle AdditionalProperties
func (a *ProviderHints) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["kubernetes"]; found {
		err = json.Unmarshal(raw, &a.Kubernetes)
		if err != nil {
			return fmt.Errorf("error reading 'kubernetes': %w", err)
		}
		delete(object, "kubernetes")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal map[string]interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProviderHints to handle AdditionalProperties
func (a ProviderHints) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Kubernetes != nil {
		object["kubernetes"], err = json.Marshal(a.Kubernetes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'kubernetes': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
